[package]
name = "shakmaty"
version = "0.19.0" # remember to update changelog and html_root_url
description = "A library for chess move generation"
repository = "https://github.com/niklasf/shakmaty"
readme = "README.md"
license = "GPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games", "parser-implementations"]
keywords = ["chess"]
build = "src/build.rs"
edition = "2018"

[features]
default = []
step = []
variant = []

[[bench]]
name = "benches"
harness = false

[lib]
bench = false

[dependencies]
bitflags = "2"
btoi = "0.4"
arrayvec = "0.7"

[dev-dependencies]
iai = "0.1"
rand = "0.8"

[build-dependencies]
rand = { version="0.8", features=["std_rng"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docs_rs"]
